# Generated by Django 5.2.8 on 2025-11-08 20:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('village', models.CharField(max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(default='Karnataka', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('ph', models.DecimalField(decimal_places=1, help_text='pH value (0-14)', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('14.0'))])),
                ('nitrogen', models.DecimalField(decimal_places=2, help_text='Nitrogen content (kg/ha)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('phosphorus', models.DecimalField(decimal_places=2, help_text='Phosphorus content (kg/ha)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('potassium', models.DecimalField(decimal_places=2, help_text='Potassium content (kg/ha)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('organic_carbon', models.DecimalField(decimal_places=2, help_text='Organic Carbon percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('moisture', models.DecimalField(decimal_places=2, help_text='Moisture percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('texture', models.CharField(blank=True, choices=[('sandy', 'Sandy'), ('loamy', 'Loamy'), ('clay', 'Clay'), ('silt', 'Silt'), ('sandy_loam', 'Sandy Loam'), ('clay_loam', 'Clay Loam'), ('silty_clay', 'Silty Clay')], max_length=20)),
                ('soil_image', models.ImageField(blank=True, null=True, upload_to='soil_images/')),
                ('season', models.CharField(blank=True, choices=[('kharif', 'Kharif (Monsoon)'), ('rabi', 'Rabi (Winter)'), ('zaid', 'Zaid (Summer)'), ('perennial', 'Perennial')], max_length=20)),
                ('crop_type', models.CharField(blank=True, help_text='Intended crop', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(choices=[('red', 'Red Soil'), ('black', 'Black Soil'), ('alluvial', 'Alluvial Soil'), ('laterite', 'Laterite Soil'), ('desert', 'Desert Soil'), ('mountain', 'Mountain Soil')], max_length=20)),
                ('fertility_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('fertility_score', models.DecimalField(decimal_places=2, help_text='Fertility score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('nitrogen_status', models.CharField(choices=[('low', 'Low'), ('adequate', 'Adequate'), ('high', 'High')], max_length=10)),
                ('phosphorus_status', models.CharField(choices=[('low', 'Low'), ('adequate', 'Adequate'), ('high', 'High')], max_length=10)),
                ('potassium_status', models.CharField(choices=[('low', 'Low'), ('adequate', 'Adequate'), ('high', 'High')], max_length=10)),
                ('recommended_crops', models.JSONField(default=list, help_text='List of recommended crops')),
                ('organic_fertilizers', models.JSONField(default=dict, help_text='Organic fertilizer recommendations')),
                ('chemical_fertilizers', models.JSONField(default=dict, help_text='Chemical fertilizer recommendations')),
                ('irrigation_tips', models.TextField(blank=True)),
                ('soil_health_tips', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Model confidence (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('100.0'))])),
                ('explanation_text', models.TextField(blank=True, help_text='Why this recommendation')),
                ('model_version', models.CharField(default='1.0', max_length=50)),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='soil_reports/pdf/')),
                ('audio_report', models.FileField(blank=True, null=True, upload_to='soil_reports/audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='soil_analysis.soilsample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilHealthHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Village, Taluk, District', max_length=200)),
                ('test_date', models.DateField()),
                ('ph_value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('nitrogen_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phosphorus_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('potassium_value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fertility_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_history', to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soil_analysis.soilsample')),
            ],
            options={
                'verbose_name_plural': 'Soil Health Histories',
                'ordering': ['farmer', 'test_date'],
            },
        ),
        migrations.CreateModel(
            name='SoilFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating 1-5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_text', models.TextField(blank=True)),
                ('is_accurate', models.BooleanField(default=True, help_text='Was the analysis accurate?')),
                ('is_helpful', models.BooleanField(default=True, help_text='Was it helpful?')),
                ('verified_by_expert', models.BooleanField(default=False)),
                ('expert_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='soil_analysis.soilsample')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='soilsample',
            index=models.Index(fields=['farmer', '-created_at'], name='soil_analys_farmer__549bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='soilsample',
            index=models.Index(fields=['district', 'taluk', 'village'], name='soil_analys_distric_781f47_idx'),
        ),
    ]
