# Generated by Django 5.2.8 on 2025-11-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropproduct',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/products/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='marketplace/products/gallery/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='original_url',
            field=models.URLField(blank=True),
        ),
    ]
